### ISSUE TITLE
Uninitialised column: 'DOI'

### ISSUE THREAD

**Issue by BenMMarshall** [Pakillo/biblioformat#2] opened 2018-09-07 11:35 UTC
Was receiving this error when running the biblioformat function. Not sure whether this was a problem specific to me, but I thought I'd be worth posting in case others run into it.

Error in biblioformat(refs) : is.character(refs.dois) is not TRUE
In addition: Warning messages:
1: Unknown or uninitialised column: 'DOI'. 
2: Unknown or uninitialised column: 'DOI'.

Easy fix within the biblioformat function. The pulling of the doi information was looking for DOI. Think this needs to be lowercase for pulling it from the data object.

refs.dois <- unlist(lapply(refs.in, function(x) {
        rcrossref::cr_works(query = x, limit = 1, sort = "score", 
            select = "DOI")$data$**doi**

`
function (refs = NULL, format = "text", style = "apa", filename = NULL, 
    ...) {
    if (is.null(refs)) {
        refs.in <- clipr::read_clip()
    }
    else refs.in <- refs
    stopifnot(is.character(refs.in))
    refs.dois <- unlist(lapply(refs.in, function(x) {
        rcrossref::cr_works(query = x, limit = 1, sort = "score", 
            select = "DOI")$data$doi
    }))
    stopifnot(is.character(refs.dois))
    refs.cit <- unlist(rcrossref::cr_cn(refs.dois, format = format, 
        style = style, ...))
    if (!is.null(filename)) 
        writeLines(refs.cit, filename)
    clipr::write_clip(refs.cit, object_type = "character")
    invisible(refs.cit)
}
`

**Comment by Pakillo** [comment] 2018-09-11 10:38
Hi @BenMMarshall 

Many thanks for reporting the error, and pointing out the solution. Yes, this is caused by recent changes in `rcrossref`. Using lowercase doi effectively fixes the problem. Fixed now

Thanks!

**Closed by Pakillo** 2018-09-11 10:38 UTC
